dist: xenial
language: cpp
compiler:
    - clang
    - gcc
      env:
        - CXX=g++-8
        - CC=gcc-8

cache:
    directories:
     - /home/travis/build/kuznetsss/Physical_simulation/build_tests
     - /home/travis/build/kuznetsss/Physical_simulation/build

install:
    - sudo apt-get update 
    - sudo apt-get install build-essential software-properties-common -y 
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
    - sudo apt-get update 
    - sudo apt-get install qt5-default valgrind tree gcc-8 g++-8
# Clone and compile google test
    - git clone --branch='release-1.8.1'  https://github.com/google/googletest
    - cd googletest
    - mkdir build
    - mkdir install
    - cd build/
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=../install
    - make -j2
    - make install
    - cd ../..

script:
    - cd build_tests
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DGTEST_ROOT="$PWD/../googletest/install"
    - make -j2 physical_simulation_tests
    - ctest --verbose
    - cd ..
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DGTEST_ROOT="$PWD/../googletest/install"
    - make -j2 physical_simulation
