dist: xenial
language: cpp
compiler: clang

install:
    - sudo apt-get update 
    - sudo apt-get install qt5-default libgtest-dev valgrind
    - mkdir build_gtest
    - cd build_gtest
    - cmake /usr/src/gtest
    - make -j2
    - sudo make install -j2 


script:
    - mkdir build_tests
    - cd build_tests
    - ctest --build-and-test .. . --build-generator 'Unix Makefiles'
    - make -j2
    - ctest --verbose
    - ctest -V -T Memcheck
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release 
    - make -j2
